### ISSUE TITLE
Capability is not set sometimes not set

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#1082]
It is possible to be super admin and don't have the role admin.
In our code we check for current_user_can( 'administrator' ). But it is possible that a super user don't have this capability

**Comment by JoryHogeveen** [comment]
Just for info. `is_super_admin()` can also be used in non-network sites in such cases. It then validated the capability `delete_users`. For network sites this validation is even faster.
Another way is to create a custom capability (`manage_admincolumns` for example) and assign it to the `administrator` role by default on installation/update. Super admins will alvast have access on network installations since they bypass all `user_can` checks.
https://developer.wordpress.org/reference/functions/is_super_admin/
https://developer.wordpress.org/reference/classes/wp_user/has_cap/
