### ISSUE TITLE
WP-CLI : add licence key

### ISSUE THREAD

**Issue by bpongy** [codepress/admin-columns-issues#1180]
Hi, it's impossible to add licence code with WP-CLI, right ?

**Comment by DGStefan** [comment]
@redpik Sorry for the late response.
Our plugin only works in the admin.
Since we need our codebase for WP-CLI that does not run in the admin, we cannot perform any of our logic on the wp-cli calls. 

Therefore it will not be possible to do this at this moment.
We have another ticket where we're going to investigate the possibility to support this.
