### ISSUE TITLE
Ordering/filtering Media library and switch between grid view and list view

### ISSUE THREAD

**Issue by remcokalf** [codepress/admin-columns-issues#1260]
I have admin columns enabled on Media.
They show only in list view, I have seen the idea to fix that:

#1240 

But there is another issue: when switching between list view and grid view some things like ordering are preserved (filtering not, or inconsistent, did not test extensively). This is very confusing for a user, as there are no admin columns in grid view.
I think as long as the admin columns are not show in grid view, all filters and ordering should be reset when switching back from list view to grid view.

**Comment by DGStefan** [comment]
@remcokalf 
I tried to reproduce this, but even with our plugin disabled, changing from a sorted list view to the grid view, give an unexpected behavior.

Expected behavior:
Items on Grid view are sorted the same as on the list view

Actual behavior:
The expected behavior works when you sort on the file name or date, but not on other columns.

This behavior applies with both our plugin enabled or disabled. Filters are already ignored, which is expected because there's no notice of that on top of the grid view, and sorting works exactly the same on the grid view.

Therefore I will reject this issue unless you have a good reason to reopen it.

**Comment by remcokalf** [comment]
I see what you mean that it also happens with AdminColumns disabled. Still It would be a nice feature of AC to reset all AC sorting en filtering in the url when clicking (back) to grid view. And of course that should also be standard WP behaviour, I agree. Thanks for looking into this.
