### ISSUE TITLE
Yoast SEO Pro: Taxonomy meta-description

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#1278]
There might be a difference between Yoast and Yoast Pro where there is a description field for taxonomies (and free does not have this?).

We do not support this description field, which should be the case if it is added in Yoast (Pro).

Requires Yoast Pro to test properly.

**Comment by NielsdeBlaauw** [comment]
After searching a bit further, this doesn't seem to be a premium only feature. Instead, the way the meta-description for a term is saved in a non intuitive way. I would expect it on `wp_termmeta`, but it's actually in an `option` called `wpseo_taxonomy_meta` as a serialized array.

**Comment by tobiasschutter** [comment]
I wonder why they choose to store this data in a single key (serialized). Maybe it's legacy when WordPress did not have the term metadata table. 

I think we will change our `editing` model to save it within the `option` table. Perhaps there is an API method we can use to make it future proof. I could see them changing the way they store this in a future release.

**Comment by DGStefan** [comment]
Let go back to the start. Our Yoast integration extends the functionality of the default Yoast columns that are already present. Although both the free and pro versions allow you to add a meta description for terms, they do not have any support for a description column on the taxonomy overview pages. So there's nothing to change on our side, since we don't have a column for meta description.

So the next questions is, are we going to create a new column for showing and editing the meta descriptions for terms.
