### ISSUE TITLE
Inline Edit: Posts selector update

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#150]
Instead of the current selector2 field to select a post, we could use the native post picker that is used by "Media" when you click "attach".

![post_picker](https://cloud.githubusercontent.com/assets/2736280/6615276/be0bc2ea-c8a2-11e4-92aa-b81a2dc9f5df.jpg)

**Comment by DGStefan** [comment]
Unfortunately there is a flaw in this solution.
This form and the working for this specific modal 'find_posts_div()' can only exist once on the page because of the use of ID's in the this form. Therefor it would not be possible to use this on the media overview for example since this one is already used for the attach media functionality.

Let's re-evaluate this when we start with the new Editing functionality
