### ISSUE TITLE
New WC column: order used coupon code

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#238]
Display in Woocommerce orders which coupon code was used if there is any.
- make the coupon code filterable.

**Comment by tobiasschutter** [comment]
added coupon code codepress/cac-addon-woocommerce@8202e29f4827f8f6f897d1d5e0b2c3496fd445e4

Next is filtering.

**Comment by DGStefan** [comment]
added used coupons for order overview
codepress/cac-addon-woocommerce@77f0d74f86578bb7cc9748423f783b5ec40cd31e

**Comment by DGStefan** [comment]
Base filtering whether coupons are used or not is added for the order overview
codepress/admin-columns-pro@143060d231a64cca6277eb9c7a037ba61490a320

I think filtering on specific coupon codes will affect the performance because there is no metafield for the coupons used for specific orders. Only a flag if on or multiple coupons are used during the proces.

**Comment by tobiasschutter** [comment]
Merged
