### ISSUE TITLE
Compile .po with gulp

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#245]
Compile all .po translations files with gulp.

(similar to grunt https://www.npmjs.com/package/grunt-wp-i18n )

Maybe this one? https://libraries.io/npm/gulp-wp-pot

Compile Po to Mo: https://www.versioneye.com/nodejs/gulp-gettext/0.1.0
https://github.com/cloud-walker/gulp-gettext

**Comment by DGStefan** [comment]
@tobiasschutter 
The please test on branche automate-po-files

The output gives less strings back compared to the original cpac.pot file.
After some research it seems that labels that were using 'cpac' domein now uses their plugin domain names. For example:

__( 'Allow, but notify customer', 'woocommerce' ) (inline-edit/classes/post.php) is now not included because of the mismatching domain. This should be correct. For deployement, please set the output folder to language instead of language/test

**Comment by rasmusbe** [comment]
Please tell me if you have any problems with gulp-wp-pot

**Comment by DGStefan** [comment]
@tobiasschutter 
use gulp compile-language to comile all po / pot files to mo.
transifex command must be used before this.

**Comment by DGStefan** [comment]
Tested for both plugins

**Comment by tobiasschutter** [comment]
Empty translations string do no longer use the default fallback english strings with the current compiler. Every string should fallback to English when empty.

**Comment by DGStefan** [comment]
There is a new commandline script in src/generate-languages

Works with empty strings
pro/branche/po-files
cpac/branche/development

**Comment by tobiasschutter** [comment]
Merged codepress/admin-columns-pro@183bcf116b7f87951a8ac787e1bebe8c2aad7506
