### ISSUE TITLE
Create a page that gives you info about the plugin as API

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#385]
- Versions
- Changelog

E.g. for acf pro I can check http://connect.advancedcustomfields.com/index.php?a=get-info&p=pro which will give me plugin info (latest version, changeling etc).

related HS ticket 2252

**Comment by pederan** [comment]
Ok, thanks. I understand this has low priority but this information would be great to able to get using a simple get call to a page that returns som basic json. 

However, since your plugin will automatically update when provided with a license code there is already a way to receive this info. I tried to dig into your code looking for how you check for updates and I found the method get_plugin_update_data in your api class. Here your method comment states: '_Get remote plugin update data in the WP format: name, slug, download_link, version_' So it looks like it already is possible to fetch this info as long as I have a license code. Can you please help me out how I can do a remote post using the correct url and body args to fetch this data?

Thanks!

**Comment by pederan** [comment]
So I did some digging and, FYI, you already have such an api. This code will return a json which will return the latest version available:

```
$args = [
    "timeout"   => 15,
    "sslverify" => false,
    "body"      => [
        "wc-api"      => "software-licence-api",
        "request"     => "plugindetails",
        "plugin_name" => "admin-columns-pro/admin-columns-pro.php"
    ]
];

$response = wp_remote_post( 'http://www.admincolumns.com', $args );
$result = json_decode( wp_remote_retrieve_body( $response ) );
print_r( $result );
```

**Comment by DGStefan** [comment]
Haha thanks, I did not realize you could use this api call :)
Of course this is meant for our license check but I don't see why you can't use it for your plugin. If you're helped with this, I will close this ticket. Good luck with your plugin.
