### ISSUE TITLE
WooCommerce Stock Column: Enable 'manage stock' when the global setting 'manage stock' is enabled.

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#670]
- Investigate the behaviour of the global setting (how does this affect single products)
- Make inline edit work with the global setting

**Comment by mugwumpr** [comment]
The global setting turns the product-level "manage stock" option on by default. This means that when the global "manage stock" option is turned on, the "manage stock" option is turned on, by default, for ALL products. 

From a beginner Woocommerce instructions site: "Check the Manage Stock option to enable stock on all products." https://www.woobeginner.com/manage-inventory-woocommerce/

Therefore, the product-level "manage stock" option is enabled for all 32K+ products, yet the plugin isn't picking up on this for any of them. 

Not so much an improvement as a problem, since it's clearly not doing what it should be doing. It should respond to the "manage stock" option on the product, but it isn't.

**Comment by DGStefan** [comment]
Issue closed since this is not a bug.

1) Global settings does not set manage_stock option for each product by default
2) This is feature that only should work with the WooCommerce addon installed.
