### ISSUE TITLE
Default columns from third party columns are removed with Admin Columns Pro

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#733]
**Use Case**
Plugin:  The Events Calendar
Without Admin Columns Pro a start date and end date column are available and are sortable by default.
When you enable Admin Columns Pro, these columns are removed, even without any layouts active.

**Update**
It turns out that the the columns are removed by using the $list_screen->get_columns() in the sorting addon -> Addon.php. When you disable the handle_sorting method all works fine.

**Comment by ikappas** [comment]
This issue affects us in a huge way since we use a lot of code defined custom columns in our projects and are all missing after updating from 3.x to 4.0.1. 

We tried disabling the handle_sorting method from the sorting addon as suggested but the columns still don't show up...

The 4.0.1 plugin is not usable for us as is.

Thank you in advance for addressing this issue swiftly.
