### ISSUE TITLE
Custom Field type "textarea"

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#780]
Add a textarea field type. This will allow the use of a textarea field when using inline edit.

And we could use Word limit as a sub settings, instead of Character limit.

**Comment by DGStefan** [comment]
Since we already done https://github.com/codepress/admin-columns-issues/issues/707 we can ask ourself if this is still necessary. 
I already made a change for this in the core and in the pro. 
https://github.com/codepress/admin-columns-pro/commit/e2fed2ea872396337a9b705f1ce81e4ba462ad9d
https://github.com/codepress/codepress-admin-columns/commit/a353b0712da2b4cb01c77c4a648cf080cdadcb4d

**Comment by DGStefan** [comment]
Closed in maintenance 4.0.12
