### ISSUE TITLE
ACF Repeater always show or formatted value of raw_value

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#787]
The problem is that some fields don't have settings with a format interface.
In that case the raw value is always shown while the get_value() of the field should be shown.
For the file subfield, this results in a ID instead of the filename that is rendered in get_value()

**Comment by davidmosterd** [comment]
I have done some research on this bug and we might need to change our way of thinking a little on how we deal with ACF. The problem is that you can't use multiple fields since the column decides what the meta-key is. While on a column-level that is great, but for a field this means there is a 1:1 relation between a column and a field. What I would like to research into a bit more is a 1:m releation between te column and the fields. Meaning: the same column can be attached as to multiple fields as a reference to the actual column, but the field does all the work in terms of sorting filtering, etc. That way we can create multiple fields runtime, attach the column to get a reference (scope) and be able to render multiple fields with help from the column (e.g. the formatting).

To accomplish this I think the column should have no knowledge of the ACF data at all. The field should function as a layer to abstract that. In that way, overlaying fields like a repeater can return proper values when a repeater e.g. has "file" as a field. 

What I prob. never going to like is that fields and columns are so tighly coupled, but I don't see a way out of that right now. (e.g. settings formatting HAS to be done in the column)

An important aspect of this solution would be how to deal with the initial 'meta-key'. The column is of the type 'meta' and as such it needs a valid return from get_meta_key, get_value, get_raw_value. Right now there is little 'trick' implemented that will (continuesly) gets the hash, then the ACF field and then distills the proper field from it.

What should be done is: create a field, add the hash (= setting ) and let the column function as a proxy for the field (e.g. clone the methods). 

As said, formatting of settings is a near static process in a column and we should look carefully to that. But this way I think we should be fine now once we call the get_value on a field directly. It can now either do it's thing directly or ask the column for help in applying the settings. This is where we might get stuck again, but maybe it will work out just fine.

**Comment by tobiasschutter** [comment]
Moved: https://github.com/codepress/ac-addon-acf/issues/74
