### ISSUE TITLE
Publish column

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#882]
Publish column with a button to instantly publish a post

**Comment by DGStefan** [comment]
I created a pullrequest for a concept for this column. Instead of only publishing a column, you can also unpublish a post. These are the scenario's in this column.

Status -> New status
Draft -> Published
Future -> Published on date Now
Pending -> Published
Published -> Draft

After publishing the post the whole row is updated.

**Comment by tobiasschutter** [comment]
I would suggest renaming a few labels as follows:

Status | New Status
------------ | -------------
Draft | Publish
Pending | Publish
Future | Publish Scheduled
Published | Draft

Also adding tooltips could help communicate the action a bit better. A tooltip for Publish to Draft would contain the text: "Change status from Published to Draft"

**Comment by tobiasschutter** [comment]
We could add a few extra buttons to make it a more versatile column. 

Extra buttons:
- [ ] Trash
- [ ] View

Maybe even renaming it to "Quick Actions". 

Another option would be to merge these buttons with the existing "Actions" column.

**Comment by tobiasschutter** [comment]
related: https://github.com/codepress/admin-columns-issues/issues/770
