### ISSUE TITLE
Updater improvements: Multsite support and forced updates

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#982]
Make updating the DB easier.

- [x] Maybe remove the confirmation, and force the update.
- [x] Multisite will have one script to run instead of on each subsite

Related ticket: https://wordpress.org/support/topic/update-in-multisite/

**Comment by davidmosterd** [comment]
This ticket is solved for 4.1.1, however, the fix is not permanent as we will have a problem once we get too many or one big update. It now just forces all the updates as they are small and should be applied in seconds.

It's marked as TODO in the code to revisit when the next update is scheduled or that we have time to properly do this.
